spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/questionnaire"
    username: "questionnaire_be_client"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      current_session_context_class: "org.springframework.orm.hibernate5.SpringSessionContext"
      jdbc.lob.non_contextual_creation: true