spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/questionnaire"
    username: "questionnaire_be_client"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      jdbc.lob.non_contextual_creation: true
questionnaire:
  token-expire-minutes: 30
  token-secret-key: secret-key